apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/jenkins
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: jenkins
      namespace: jenkins
  timeout: 5m0s
