apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: jenkins
  namespace: flux-system
spec:
  interval: 53m
  retryInterval: 10m
 #suspend: true
  path: ./apps/jenkins
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: ingress-nginx
    - name: persistence
    - name: my-secrets
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: jenkins
      namespace: jenkins
  timeout: 6m0s
  validation: client
  wait: true
  patches:
    - target:
        kind: HelmRelease
        name: jenkinsci
        namespace: flux-system
      patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: jenkinsci
        spec:
          postRenderers:
          - kustomize:
              patchesStrategicMerge:
                - kind: StatefulSet
                  apiVersion: apps/v1
                  metadata:
                    name: jenkins
                    namespace: jenkins
                  spec:
                    replicas: 1
          values:
            persistence:
              enabled: true
              #existingClaim: jenkins-precreated
            controller:
              # image: kingdonb/jenkins # {"$imagepolicy": "flux-system:jenkins:image"}
              # tag: lts-5e87b83f-1630687511 # {"$imagepolicy": "flux-system:jenkins:tag"}
              #installPlugins: false
              #installPlugins:
              #  - kubernetes
              #  - workflow-aggregator
              #  - git
              #  - configuration-as-code
              #  - authorize-project
              #  - github-oauth
              #  - command-launcher
              #  - jdk-tool
              #  - job-dsl
              #  - strict-crumb-issuer
              # find additional configuration at: ../../../apps/jenkins/helmrelease.yaml
