apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: jenkins-scale
  namespace: flux-system
spec:
  interval: 22h15m
  retryInterval: 10m
  timeout: 9m0s
 #suspend: true
  path: ./apps/jenkins-scale
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: jenkins
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: jenkins
      namespace: jenkins
