apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - gotk-components.yaml
# - gotk-sync.yaml
# - cert-manager-sync.yaml
- slack-notification.yaml
- gitno-hephy-pro-ingress.yaml
- git-webhook-receiver.yaml
- image-webhook-receiver.yaml
- on-call-webapp-alert.yaml
patchesStrategicMerge:
- gotk-patches.yaml
