apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- controller-configmap.yaml
- controller-deployment.yaml
- controller-ingressclass.yaml
- controller-role.yaml
- controller-rolebinding.yaml
- controller-service-webhook.yaml
- controller-service.yaml
- controller-serviceaccount.yaml
- admission-webhooks/job-patch/clusterrole.yaml
- admission-webhooks/job-patch/clusterrolebinding.yaml
- admission-webhooks/job-patch/job-createSecret.yaml
- admission-webhooks/job-patch/job-patchWebhook.yaml
- admission-webhooks/job-patch/role.yaml
- admission-webhooks/job-patch/rolebinding.yaml
- admission-webhooks/job-patch/serviceaccount.yaml
- admission-webhooks/validating-webhook.yaml
