---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 613m17s
  retryInterval: 10m0s
  path: ./gitops/flux/apps/source/podinfo
  dependsOn:
    - name: linkerd-finally
  prune: true
  sourceRef:
    kind: GitRepository
    name: linkerd-demos
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: podinfo
      namespace: podinfo
    - apiVersion: apps/v1
      kind: Deployment
      name: generator
      namespace: podinfo
    - apiVersion: apps/v1
      kind: Deployment
      name: frontend
      namespace: podinfo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-dev-hosts
  namespace: flux-system
spec:
  interval: 613m1s
  retryInterval: 10m0s
  path: ./gitops/flux/apps/source/podinfo-dev
  dependsOn:
    - name: linkerd-finally
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: linkerd-demos
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: emojivoto
  namespace: flux-system
spec:
  interval: 331m12s
  retryInterval: 10m0s
  path: ./gitops/flux/apps/source/emojivoto
  dependsOn:
    - name: linkerd-finally
  prune: true
  sourceRef:
    kind: GitRepository
    name: linkerd-demos
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: emoji
      namespace: emojivoto
    - apiVersion: apps/v1
      kind: Deployment
      name: vote-bot
      namespace: emojivoto
    - apiVersion: apps/v1
      kind: Deployment
      name: web
      namespace: emojivoto
    - apiVersion: apps/v1
      kind: Deployment
      name: voting
      namespace: emojivoto
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: booksapp
  namespace: flux-system
spec:
  interval: 863m14s
  retryInterval: 10m0s
  path: ./gitops/flux/apps/source/booksapp
  dependsOn:
    - name: linkerd-finally
  prune: true
  sourceRef:
    kind: GitRepository
    name: linkerd-demos
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: traffic
      namespace: booksapp
    - apiVersion: apps/v1
      kind: Deployment
      name: webapp
      namespace: booksapp
    - apiVersion: apps/v1
      kind: Deployment
      name: authors
      namespace: booksapp
    - apiVersion: apps/v1
      kind: Deployment
      name: books
      namespace: booksapp
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: deis-hosts
  namespace: flux-system
spec:
  interval: 863m14s
  retryInterval: 10m0s
  path: ./gitops/flux/apps/source/deis
  dependsOn:
    - name: ambassador
  prune: true
  sourceRef:
    kind: GitRepository
    name: linkerd-demos
  healthChecks:
    - apiVersion: getambassador.io/v2
      kind: Host
      name: deis
      namespace: default
    - apiVersion: getambassador.io/v2
      kind: Mapping
      name: deis
      namespace: deis
